name: Branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout changes"
        uses: actions/checkout@v2
      - name: "Build"
        run: "yarn install && yarn lerna bootstrap && yarn lerna run build"
      - name: "Test"
        run: "yarn install && yarn lerna bootstrap && yarn lerna run test"
      - name: "Lint"
        run: "yarn install && yarn lerna bootstrap && yarn lerna run lint"
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Checkout changes"
  #       uses: actions/checkout@v2
  #     - name: "Test"
  #       run: "yarn install && yarn lerna bootstrap && yarn lerna run test"
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Checkout changes"
  #       uses: actions/checkout@v2
  #     - name: "Lint"
  #       run: "yarn install && yarn lerna bootstrap && yarn lerna run lint"
