name: Publish

on: [push]

jobs:
  publish:
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout changes"
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: "Show config"
        run: "git config --list"
      - name: "Publish changes"
        uses: Vertexvis/npm-publish-action@v1
        with:
          npm-registry: "npm.ops.vertexvis.io"
          npm-auth-token: ${{ secrets.PRIVATE_NPM_AUTH_TOKEN }}
